language: php
php:
  - '7.1'

before_script:
  - composer install --prefer-source --no-interaction --dev

script: vendor/phpunit/phpunit/phpunit --configuration phpunit.xml.dist

notifications:
    on_success: never
    on_failure: always
